language: rust

# from https://levans.fr/rust_travis_cache.html
cache:
    directories:
        - /home/travis/.cargo
        - $SDL_DIR
before_cache:
    - rm -rf /home/travis/.cargo/registry

before_install:
    - sudo apt install libbullet-dev
addons:
    apt:
        update: true

# ---

branches:
    only:
        - develop
        - master
        - feature/#30-fix-travis

install:
    - bash .travis-install-sdl2.sh

env:
    SDL_DIR=SDL2-2.0.9
os:
    - linux
      # TODO windows and osx
rust:
    - stable


#matrix:
#  fast_finish: true
#  allow_failures:
#  include:
#    - env: NAME='cargo-travis'
#      sudo: required # travis-ci/travis-ci#9061
#      before_script:
#        - cargo install cargo-update || echo "cargo-update already installed"
#        - cargo install cargo-travis || echo "cargo-travis already installed"
#        - cargo install-update -a
#      script:
#        - |
#          cargo build --verbose &&
#          cargo coverage --verbose # &&
#          bash <(curl -s https://codecov.io/bash) -s target/kcov
#      addons: # required for kcov
#        apt:
#          packages:
#            - libcurl4-openssl-dev
#            - libelf-dev
#            - libdw-dev
#            - binutils-dev
#            - cmake

script: |
        export RUST_BACKTRACE=1 &&
        cargo build --verbose --all &&
        cargo test --verbose --all
