language: rust

# from https://levans.fr/rust_travis_cache.html
cache:
    directories:
        - /home/travis/.cargo
        - $SDL_DIR
before_cache:
    - rm -rf /home/travis/.cargo/registry

branches:
    only:
        - /.*/

install:
    - if [[ "$TRAVIS_BRANCH" = "develop" && -f .planning/active.md ]]; then echo "develop should not have an active.md"; exit 1; fi
    - bash .travis-install-sdl2.sh

env:
    SDL_DIR=SDL2-2.0.9
os:
    - linux
      # TODO windows and osx
rust:
    - stable
    - nightly

jobs:
    allow_failures:
        - rust: nightly

# sfml
script: |
        export PATH=$PATH:/usr/local/lib &&
        env &&
        export RUST_BACKTRACE=1 &&
        export NN_LOG=debug &&
        cargo build --verbose --workspace &&
        cargo test --verbose --workspace &&
        cargo test --verbose -- --ignored &&
        cd renderer/main && cargo run --verbose --features lite --no-default-features -- --preset dev --dir ../../
