language: rust

# from https://levans.fr/rust_travis_cache.html
cache:
    directories:
        - /home/travis/.cargo
        - $SFML_INSTALL
before_cache:
    - rm -rf /home/travis/.cargo/registry

branches:
    only:
        - develop
        - master

install:
    - bash .travis-install-sfml.sh

env:
  global:
    - SFML_INSTALL=$TRAVIS_BUILD_DIR/SFML/sfml_install
    - LIBRARY_PATH=$SFML_INSTALL/usr/local/lib
    - LD_LIBRARY_PATH=$SFML_INSTALL/usr/local/lib
os:
    - linux
      # TODO windows and osx
rust:
    - stable
    - nightly

# sfml
addons:
  apt:
    packages:
    - libpthread-stubs0-dev
    - libgl1-mesa-dev
    - libx11-dev
    - libx11-xcb-dev
    - libxcb-image0-dev
    - libxrandr-dev
    - libxcb-randr0-dev
    - libudev-dev
    - libfreetype6-dev
    - libglew-dev
    - libjpeg8-dev
    - libgpgme11-dev
    - libsndfile1-dev
    - libopenal-dev
    - libjpeg62
    - cmake

#matrix:
#  fast_finish: true
#  allow_failures:
#  include:
#    - env: NAME='cargo-travis'
#      sudo: required # travis-ci/travis-ci#9061
#      before_script:
#        - cargo install cargo-update || echo "cargo-update already installed"
#        - cargo install cargo-travis || echo "cargo-travis already installed"
#        - cargo install-update -a
#      script:
#        - |
#          cargo build --verbose &&
#          cargo coverage --verbose # &&
#          bash <(curl -s https://codecov.io/bash) -s target/kcov
#      addons: # required for kcov
#        apt:
#          packages:
#            - libcurl4-openssl-dev
#            - libelf-dev
#            - libdw-dev
#            - binutils-dev
#            - cmake

script: |
        export PATH=$PATH:/usr/local/lib &&
        env &&
        ls -l $SFML_INSTALL/usr/local/lib &&
        export RUST_BACKTRACE=1 &&
        export NN_LOG=debug &&
        cargo build --verbose --workspace &&
        cargo test --verbose --workspace &&
        cargo test --verbose -- --ignored &&
        cd renderer/main && cargo run --verbose --features lite --no-default-features -- --preset dev --dir ../../
