[workspace]

members = [
	"engine",
	"gameloop",
	"world",
	"tweaker",
	"simulation",
	"unit",
	"physics",
	"physics/bulletc-sys",
	"physics/debug-draw",
]

# "temporary" fix for building without parallelization https://github.com/amethyst/specs/issues/642
[patch.crates-io]
shred = { git = "https://github.com/mystal/shred.git", branch = "fix_no_parallel", default-features = false }
