[workspace]

members = [
	"game/ai",
	"game/simulation",
	"game/world",

	"renderer/engine",
	"renderer/gameloop",
	"renderer/main",

	"shared/color",
	"shared/common",
	"shared/config",
	"shared/metrics",
	"shared/struclog",
	"shared/unit",
]

[profile.dev]
debug = 0 # for fasting build times

[profile.release]
debug = 1 # for profiling
