[workspace]

members = [
	"game/physics",
	"game/physics/bulletc-sys",
	"game/physics/debug-draw",
	"game/simulation",
	"game/world",

	"renderer/engine",
	"renderer/gameloop",
	"renderer/main",

	"shared/color",
	"shared/common",
	"shared/config",
	"shared/struclog",
	"shared/unit",
]

[profile.dev]
debug = 0
