[workspace]

members = [
	"game",
	"game-presets",
	"engine",
	"gameloop",
	"world",
	"config",
	"common",
	"simulation",
	"unit",
	"physics",
	"physics/bulletc-sys",
	"physics/debug-draw",
]

[profile.dev]
#debug = 0
