[package]
name = "definitions"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
simulation = { path = "../../game/simulation", features = ["utils"] }
resources = { path = "../../game/resources" }
logging = { path = "../../shared/logging", features = ["to-file"] }
