[package]
name = "world"
version = "0.1.0"
authors = ["Dom Williams <me@domwillia.ms>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
generator = "0.6"
scale = {path = "../scale"}
petgraph = "0.4"
float-cmp = "0.5"
cgmath = "0.17"
nd_iter = "0.0.4"
log = "0.4"
