[package]
name = "world_types"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../../../shared/common" }
color = { path = "../../../shared/color" }
unit = { path = "../../../shared/unit" }
world = { path = "../../world" }

strum = { version = "0.19", features = ["derive"] }
