[package]
name = "engine"
version = "0.1.0"
authors = ["Dom Williams <me@domwillia.ms>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# removed until cargo-travis uses cargo 0.37+
# default-run = "engine"

[dependencies]
gameloop = {path = "../gameloop"}
simulation = {path = "../../game/simulation"}

config = {path = "../../shared/config"}
unit = {path = "../../shared/unit"}
common = {path = "../../shared/common"}
color = {path = "../../shared/color"}

sfml = {version = "^0.15", git = "https://github.com/jeremyletang/rust-sfml", optional = true}
take_mut = "^0.2"

[features]
default = []
use-sfml = ["sfml"]
lite = []
