[package]
name = "simulation"
version = "0.1.0"
authors = ["Dom Williams <me@domwillia.ms>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["dylib"]

[dependencies]
world = {path = "../world"}
physics = {path = "../physics"}
debug-draw = { path = "../physics/debug-draw" }

unit = {path = "../../shared/unit"}
config = {path = "../../shared/config"}
common = { path = "../../shared/common", features=["library"] }
color = { path = "../../shared/color" }

legion = "^0.2"
