[package]
name = "procgen"
version = "0.1.0"
authors = ["Dom Williams <me@domwillia.ms>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = {path = "../../shared/common"}
noise = "^0.6"
image = {version = "^0.23", optional = true}

[features]
default = ["bin"]
bin = ["image"]