name: Build and test

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest] # TODO macos too

    name: Build and test on ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v3.x

    - name: Ensure .planning is correct
      run:  ./.build/check-planning.sh
      shell: bash

    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
    - name: Setup Rust cache
      uses: Swatinem/rust-cache@v1

    - name: Build and run unit tests
      run: ./.build/run-tests.sh
      shell: bash

    - name: Build and run headless game
      run: ./.build/run-headless.sh
      shell: bash
